-- migrate:up

ALTER TABLE arkhamdb_decklist ALTER COLUMN investigator_code TYPE VARCHAR(255);
ALTER TABLE arkhamdb_decklist ALTER COLUMN canonical_investigator_code TYPE VARCHAR(255);

ALTER TABLE card ALTER COLUMN alternate_of_code TYPE VARCHAR(255);
ALTER TABLE card ALTER COLUMN back_link_id TYPE VARCHAR(255);
ALTER TABLE card ALTER COLUMN code TYPE VARCHAR(255);
ALTER TABLE card ALTER COLUMN duplicate_of_code TYPE VARCHAR(255);
ALTER TABLE card ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE card ALTER COLUMN pack_code TYPE VARCHAR(255);

ALTER TABLE card_resolution ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE card_resolution ALTER COLUMN resolves_to TYPE VARCHAR(255);

ALTER TABLE cycle ALTER COLUMN code TYPE VARCHAR(255);

ALTER TABLE encounter_set ALTER COLUMN code TYPE VARCHAR(255);
ALTER TABLE encounter_set ALTER COLUMN pack_code TYPE VARCHAR(255);

ALTER TABLE pack ALTER COLUMN code TYPE VARCHAR(255);
ALTER TABLE pack ALTER COLUMN cycle_code TYPE VARCHAR(255);

-- migrate:down
